---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  stylelint:
    enabled: false
  phpcodesniffer:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths: []
